######################################################################
# Automatically generated by qmake (3.1) Sat May 25 13:37:39 2019
######################################################################

TEMPLATE = app
QT -= gui
QT += sql
TARGET = sqlite-tablecache
INCLUDEPATH += .
HEADERS += TableCache.h CarCache.h DbScopeCached.h
SOURCES += main.cpp CarCache.cpp DbScopeCached.cpp
QMAKE_LFLAGS += -lsqlite3
